In [1]:
import pandas as pd

# Define sample data
# i_data = {
#     'unique_id': range(1, 13),
#     'first_name': ['John', 'Jane', 'David', 'Emily', 'Michael', 'Sarah', 'John', 'Jane', 'David', 'Emily', 'John', 'John'],
#     'last_name': ['Doe', 'Smith', 'Johnson', 'Brown', 'Davis', 'Miller', 'Doe', 'Smith', 'Johnson', 'Brown', 'Miller', 'Jones'],
#     'full_name': ['John Doe', 'Jane Smith', 'David Johnson', 'Emily Brown', 'Michael Davis', 'Sarah Miller', 'John Doe', 'Jane Smith', 'David Johnson', 'Emily Brown', 'John Miller', 'John Jones'],
#     'entity_type': ['Person'] * 12,
#     'state': ['CA', 'NY', 'TX', 'FL', 'CA', 'NY', 'CA', 'TX', 'FL', 'NY', 'CA', 'FL'],
#     'party': ['Democrat', 'Republican', 'Independent', 'Democrat', 'Republican', 'Independent', 'Democrat', 'Republican', 'Independent', 'Democrat', 'Republican', 'Independent'],
#     'company': ['Apple', 'Google', 'Microsoft', 'Amazon', 'Facebook', 'Apple', 'Google', 'Microsoft', 'Amazon', 'Facebook', 'Google', 'Microsoft']
# }

# Create DataFrame
df_i = pd.read_csv('complete_individuals_table.csv')
df_i.rename(columns={'id': 'unique_id'}, inplace=True)

/Users/naynapashilkar/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/naynapashilkar/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
/var/folders/nk/h__9839s2k1_48m_z2g76vn40000gn/T/ipykernel_4396/3624639948.py:16: DtypeWarning: Columns (8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_i = pd.read_csv('complete_individuals_table.csv')

In [2]:
df_i

,Unnamed: 0,unique_id,first_name,last_name,full_name,entity_type,state,party,company,occupation,address,zip,city
0,0,efa41f9a-a31c-4154-acfa-3707d2c7cc47,FREDERICK,BERG,FREDERICK BERG ...,Individual,MI,NaN,BUTZEL LONG,ATTORNEY,1033 YORKSHIRE,48230-0000,GROSSE POINTE PARK
1,1,3e7661e4-1557-4fc8-9cd7-e4381eaed2d8,JENNIFER,CONSIGLIO,JENNIFER CONSIGLIO ...,Individual,MI,NaN,BUTZEL LONG,ATTORNEY,7520 SHUMAN DRIVE,48438-0000,GOODRICH
2,2,a3bbe060-5da0-4b1d-a61c-0a32ec18c2ed,VANESSA,CROCETTO,VANESSA CROCETTO ...,Individual,MI,NaN,BUTZEL LONG,CHIEF MARKETING OFFICER,4104 ARLINGTON DRIVE,48073-0000,ROYAL OAK
3,3,667ae9be-5aff-4ce2-a032-5947032c1a9a,CAREY A.,DEWITT,CAREY A. DEWITT ...,Individual,MI,NaN,BUTZEL LONG,ATTORNEY,770 HUPP CROSS ROAD,48301-0000,BLOOMFIELD TWP
4,4,f02b191a-235a-4d79-9e00-3fd63a249e66,JENNIFER,DUKARSKI,JENNIFER DUKARSKI ...,Individual,MI,NaN,NaN,NaN,11855 BECK ROAD,48170-0000,PLYMOUTH
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2486933,2486933,67a8b2e6-3ff2-4d9d-a049-545202df393e,GRETCHEN,WHITMER,GRETCHEN WHITMER,Candidate,MI,NaN,NaN,NaN,NaN,NaN,NaN
2486934,2486934,67a8b2e6-3ff2-4d9d-a049-545202df393e,GRETCHEN,WHITMER,GRETCHEN WHITMER,Candidate,MI,NaN,NaN,NaN,NaN,NaN,NaN
2486935,2486935,67a8b2e6-3ff2-4d9d-a049-545202df393e,GRETCHEN,WHITMER,GRETCHEN WHITMER,Candidate,MI,NaN,NaN,NaN,NaN,NaN,NaN
2486936,2486936,67a8b2e6-3ff2-4d9d-a049-545202df393e,GRETCHEN,WHITMER,GRETCHEN WHITMER,Candidate,MI,NaN,NaN,NaN,NaN,NaN,NaN
2486937,2486937,67a8b2e6-3ff2-4d9d-a049-545202df393e,GRETCHEN,WHITMER,GRETCHEN WHITMER,Candidate,MI,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
from splink.duckdb.linker import DuckDBLinker
import altair as alt
alt.renderers.enable('html')

RendererRegistry.enable('html')

In [4]:
import splink.duckdb.comparison_template_library as ctl
import splink.duckdb.comparison_library as cl

individual_settings = {
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        "l.full_name - r.full_name",
        "l.first_name = r.first_name and l.last_name = r.last_name"
    ],
    # "comparisons": [
    #     ctl.name_comparison("first_name"), #built in comparison function
    #     ctl.name_comparison("last_name"),
    #     ctl.name_comparison("full_name"),
    #     ctl.forename_surname_comparison("first_name", "last_name"), #built in comparison function
    #     cl.exact_match("entity_type", term_frequency_adjustments=True),
    #     cl.jaro_winkler_at_thresholds("state", [0.9, 0.8]), #threshold will catch typos and shortenings
    #     cl.jaro_winkler_at_thresholds("party", [0.9, 0.8]),
    #     cl.jaro_winkler_at_thresholds("company", [0.9, 0.8]),
    # ],
    
    #DEFAULT
    "retain_matching_columns": True,
    "retain_intermediate_calculation_columns": True,
    # "max_iterations": 10,
    # "em_convergence": 0.01
}

i_blocking = [
            "l.first_name = r.first_name and l.last_name = r.last_name",
        ]

In [5]:
linker = DuckDBLinker(df_i, individual_settings)
linker.count_num_comparisons_from_blocking_rule("l.first_name = r.first_name and l.last_name = r.last_name")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

0

In [8]:
def splink_dedupe(df, settings, blocking):
    linker = DuckDBLinker(df, settings)
    linker.estimate_probability_two_random_records_match(blocking, recall=0.6) #default
    linker.estimate_u_using_random_sampling(max_pairs=5e6)
    
    for i in blocking:
        training_session_names = linker.estimate_parameters_using_expectation_maximisation(i)
    
    df_predict = linker.predict()
    df_e = df_predict.as_pandas_dataframe()
    clusters = linker.cluster_pairwise_predictions_at_threshold(df_predict, threshold_match_probability=0.7) #default
    return clusters.as_pandas_dataframe()

In [9]:
splink_dedupe(df_i, individual_settings, i_blocking)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

WARNING: Deterministic matching rules led to no observed matches! This means that no possible record pairs are matches, and no records are linked to one another.
If this is truly the case then you do not need to run the linkage model.
However this is usually in error; expected rules to have recall of 60%. Consider revising rules as they may have an error.
Probability two random records match is estimated to be  0.
This means that amongst all possible pairwise record comparisons, one in Infinity are expected to match.  With 3,092,429,064,453 total possible comparisons, we expect a total of around 0.00 matching pairs
----- Estimating u probabilities using random sampling -----

Estimated u probabilities using random sampling

Your model is fully trained. All comparisons have at least one estimate for their m and u values

----- Starting EM training session -----

Estimating the m probabilities of the model by blocking on:
l.first_name = r.first_name and l.last_name = r.last_name

Parameter estimates will be made for the following comparison(s):

Parameter estimates cannot be made for the following comparison(s) since they are used in the blocking rules:

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

EMTrainingException: Training rule `l.first_name = r.first_name and l.last_name = r.last_name` resulted in no record pairs.  This means that in the supplied data set there were no pairs of records for which `l.first_name = r.first_name and l.last_name = r.last_name` was `true`.
Expectation maximisation requires a substantial number of record comparisons to produce accurate parameter estimates - usually at least a few hundred, but preferably at least a few thousand.
You must revise your training blocking rule so that the set of generated comparisons is not empty.  You can use `linker.count_num_comparisons_from_blocking_rule()` to compute the number of comparisons that will be generated by a blocking rule.

In [ ]:
#--------------------------------------------

In [ ]:
organizations_settings = {
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        "l.name = r.name",
    ],
    "comparisons": [
        ctl.name_comparison("name", term_frequency_adjustments=True),
        cl.exact_match("entity_type", term_frequency_adjustments=True),
        cl.jaro_winkler_at_thresholds("state", [0.9, 0.8]), #threshold will catch typos and shortenings
        # Add more comparisons as needed
    ],
    "retain_matching_columns": True,
    "retain_intermediate_calculation_columns": True,
    "max_iterations": 10,
    "em_convergence": 0.01
}

o_blocking = [
            "l.name = r.name",
            "l.name = r.name and l.state = r.state",
        ]

In [ ]:

# Define sample data
o_data = {
    'unique_id': range(1, 13),
    'name': ['Apple Inc.', 'Google LLC', 'Microsoft Corporation', 'Amazon.com Inc.', 'Facebook Inc.', 
             'Apple Inc.', 'Google LLC', 'Microsoft Corporation', 'Amazon.com Inc.', 'Facebook Inc.', 
             'Google LLC', 'Microsoft Corporation'],
    'entity_type': ['Organization'] * 12,
    'state': ['CA', 'NY', 'WA', 'WA', 'CA', 'CA', 'NY', 'WA', 'WA', 'CA', 'NY', 'WA'],
}

# Create DataFrame
df_o = pd.DataFrame(o_data)

In [ ]:
splink_dedupe(df_o, organizations_settings, o_blocking)